# Generated by Django 4.2.4 on 2023-08-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=15)),
                ('matricula', models.IntegerField()),
                ('profesion', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('sector', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('sector', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField()),
                ('turno', models.DateField()),
            ],
        ),
    ]
