# Generated by Django 4.2.4 on 2023-09-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_medicos_options_alter_personal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnos',
            options={'ordering': ['turno'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
    ]
